# /home/ryotaro/dev/mnp-dw-20250821/docker-compose.yml
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    # env_file で .env.local を読み込む
    env_file:
      - .env
    # env.localはローカル以外では不要のため.envに修正(本当はなくてもいい)
    # environment は“値を持つものだけ”を書く（無指定キーは削除）
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"      # 必要なら
      CHOKIDAR_USEPOLLING: "true"    # 必要なら
    # ここ（サービス配下）に置く
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  node_modules:
