# /home/ryotaro/dev/mnp-dw-20250821/payload/docker-compose.yml

services:
  payload:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: payload-app
    working_dir: /usr/src/app
    mem_limit: 2g
    memswap_limit: 2g

    env_file:
      - ../.env.local

    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=1024

    restart: unless-stopped

    ports:
      - "3100:3000"

    volumes:
      - node_modules_cache:/usr/src/app/node_modules   # 依存キャッシュ（ビルド高速化）
      - ./media:/usr/src/app/media                     # アップロードファイル永続化

    command: >
      sh -lc "
        if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then
          (npm ci || npm install --production);
        fi &&
        npx payload generate:types &&
        npx payload generate:importmap &&
        npm run start
      "

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 15s

volumes:
  node_modules_cache:
